---
title: "PrimeR"
---

# Where to begin?

1. Download and install R    
  There are two distributions to chose from:  
    i.  [CRAN](https://cran.r-project.org/)    
      - Plus: Current release   
      - Minus: Parallel computing requires setup  
      
    ii. [Microsoft Open R](https://mran.microsoft.com/download)   
      - Plus: Uses the Intel MKL for parallel computing  
      - Minus: Not the current release  
      - Depends: Package repository is fixed to release date of current
      MRAN version  
    
2. Install an 
[IDE](https://en.wikipedia.org/wiki/Integrated_development_environment)  
  [RStudio](https://www.rstudio.com/products/rstudio/download/#download)
  is the best. You can also use VisualStudio or the command line if you
  wanted.  

3. Add packages & 
  [install RTools](https://cran.r-project.org/bin/windows/Rtools/)
  You'll need this at some point, just bite the bullet and do it now.  
  
  R comes installed with a variety of excellent tools, but really shines
  with the addition of external packages. There are ~ 14,000
  packages available for R. If you need to do it, from importing a
  spreadsheet to Disease-Gene-Variant Relations Mining, there's likely a
  package to help. 
  
  
These packages are used in the model and data analysis demonstrations:

```
install.packages(c("devtools",
                   "tidyverse",
                   "data.table",
                   "Boruta",
                   "caret",
                   "caTools",
                   "DiagrammeR",
                   "DT",
                   "ggridges",
                   "glmnet",
                   "kernlab",
                   "knitr",
                   "kableExtra",
                   "ranger",
                   "RForcecom",
                   "tokenizers",
                   "xgboost"),
                  repos = "https:://cloud.r-project.org",
                  dependencies = T)
                  
```
                  
The demonstration model uses development versions of these tidymodels
packages. They can be installed from [github](https:://github.com). 

```
devtools::install_github("tidymodels/dials")
devtools::install_github("tidymodels/parsnip")
devtools::install_github("tidymodels/recipes")
devtools::install_github("tidymodels/rsample")
devtools::install_github("tidymodels/yardstick")

```
  
# Resources

## Book learning  

[R for Data Science](http://r4ds.had.co.nz/) by Hadley Wickham is the
*best book* available. It starts with working with data frames (think
spreadsheet) and works backwards. This gets you doing work quickly and
then digs deeper and deeper as you go.  

[Data Smart](http://www.john-foreman.com/data-smart-book.html) by 
John Foreman works through modeling in Excel so you can *see* how the
math works. It's how I got my head wrapped around data science. 

## Support 

If something doesn't work Google and 
[Stack Overflow](https://stackoverflow.com/) are your friends.

You can also get help by asking R. Type ?sqrt and R will tell you what
the function sqrt does. 

Built with R
`r getRversion()`  
